import os

# _LICENSE_OPTIONS = [
#     "CC0",
#     "MIT",
#     "Apache 2",
#     "CC BY 4.0",
#     "CC BY-SA 4.0",
#     "CC BY-NC 4.0",
#     ""
# ]

_PRESENT_COLS = ["Name", "Followers", "Num Posts", "Avg Likes", "Avg Shares", "Start Date", "End Date"]

_LICENSE_GROUPINGS = {
    "CC0": ["CC0", "CC0 1.0", "Public Domain"],
    "MIT / Apache 2": ["MIT", "Apache 2", "Apache 2.0", "BSD",],
    "CC BY": ["CC BY 4.0", "CC BY-SA 4.0", "CC BY-SA 3.0", ],
    "CC BY NC": ["CC BY-NC 4.0", "CC BY-NC-SA 4.0", "CC BY-NC-ND 4.0", "CC BY-NC-SA 3.0"],
    "GPL": ["GPL 3.0"],
    "Other / Unspecified": ["Custom", "Unspecified", "Unknown"]
    # "Other / Unspecified": [],
}

_LANGUAGE_GROUPS = {
    "English": ["English"],
    "French": ["French"],
    "Spanish": ["Spanish"],
    "Hindi": ["Hindi"],
    "German": ["German"],
    "Chinese": ["Chinese"],
    "Arabic": ["Arabic"],
    "Japanese": ["Japanese"],
    "Persian": ["Persian"],
    "Afro-Asiatic": ["Somali"],
    "Austronesian": ["Indonesian",],
    "Austroasiatic": ["Vietnamese"],
    "Turkish": ["Turkish"],
    "Other Indo-European": ["Italian", "Portuguese", "Catalan", "Russian", "Polish", "Czech", "Romanian", "Dutch", "Galician", "Bulgarian", "Croatian", "Slovak"],
    "Indian Peninsula": ["Bengali", "Telugu", "Nepali", "Kurdish", "Tamil", "Gujarati"],
    "Scandinavian": ["Finnish", "Swedish"],
    "Low Resource Languages": ["Haitian", "Malayalam", "Xhosa", "Yoruba", "Zhuang"],
}

_TASK_CATEGORY_GROUPS = {
    'Question Answering': [
        "Question Answering", "Multiple-Choice QA (no trivia knowledge required)", "Extractive QA", "Closed-Book QA",
        "Information Extraction", "Question Understanding"],
    "Translation": ["Translation", "Inverted Translation"],
    "Sentiment Analysis": ["Sentiment Analysis"],
    "Summarization": ["Summarization"],
    "Text Classification": [
        "Text Categorization", "Title Generation", "Named Entity Recognition", "Coreference Resolution",
        "Cause Effect Classification", "Text Matching"],
    "Natural Language Inference": ["Natural Language Inference", "Textual Entailment"],
    "Question Generation": [
        "Question Generation", "Inverted Multiple-Choice QA (no trivia knowledge required)", "Inverted Extractive QA"],
    "Toxic Language Detection": ["Toxic Language Detection"],
    "Chain-of-Thought": ["Chain-of-Thought"],
    "Dialog Generation": ["Dialogue Generation"],
    "Code Generation": ["Text to Code"],
    "Short Text Generation": ["Text Completion", "Misc.", "Paraphrasing", "Sentence Composition"],
    "Open-form Text Generation": [
        "Inverted Natural Language Inference", "Inverted Summarization", "Inverted Sentiment Analysis",
        "Structured Data to Text"],
    "Other Tasks": [
        "Speaker Identification",
        "Inverted Structured Data to Text",
        "Wrong Candidate Generation",
        "Inverted Coreference Resolution",
        "Story Composition",
        "Pos Tagging",
        "Data to Text",
        "Topic Classification",
        "Inverted Closed-Book QA",
        "Inverted Next Sentence Prediction",
        "Next Sentence Prediction",
        "Paraphrasing Identification",
        "Inverted Paraphrasing Identification",
        "Answer Verification",
        "Text Simplification",
        "Commonsense Classification",
        "Program Execution",
        "Word Relation Classification",
        "Question Rewriting",
        "Fact Verification",
        "Dialogue Act Recognition",
        "Sentence Perturbation",
        "Word Semantics",
        "Dialog Context Generation",
        "Conversational Question Answering",
        "Inverted Topic Classification",
        "Text Quality Evaluation",
        "Mathematical QA",
        "Inverted Mathematical QA",
        "Coherence Classification",
        "Explanation",
        "Answerability Classification",
        "Linguistic Probing",
        "Stance Detection",
        "Dialogue State Tracking",
        "Gender Classification",
        "Grammar Error Correction",
        "Language Identification",
        "Fill in The Blank",
        "Keyword Tagging",
        "Inverted Grammatical Acceptability",
        "Grammatical Acceptability",
        "Inverted Punctuation Fixing",
        "Punctuation Fixing",
        "Inverted Language Modeling",
        "Language Modeling",
        "Casing Selection",
        "Inverted Casing Selection",
        "Inverted Question Answering",
        "Word Sense Disambiguation",
        "Inverted Word Sense Disambiguation",
        "Word Segmentation",
        "Inverted Word Segmentation",
        "Adversarial QA",
        "Context Generation",
        "Explanation Generation",
        "Dialog Turn Prediction",
        "Span Generation",
        "Intent Identification",
        "Word Analogy",
        "Question Decomposition",
        "Negotiation Strategy Detection",
        "Grammar Error Detection",
        "Stereotype Detection",
        "Style Transfer",
        "Entity Generation",
        "Number Conversion",
        "Sentence Compression",
        "Paper Review",
        "Overlap Extraction",
        "Poem Generation",
        "Preposition Prediction",
        "Ethics Classification",
        "Irony Detection",
        "Spam Classification",
        "Sentence Ordering",
    ]
}