# _LICENSE_OPTIONS = [
#     "CC0",
#     "MIT",
#     "Apache 2",
#     "CC BY 4.0",
#     "CC BY-SA 4.0",
#     "CC BY-NC 4.0",
#     ""
# ]


LICENSE_GROUPS = {
    "CC0": ["CC0", "CC0 1.0", "Public Domain"],
    "MIT / Apache 2": ["MIT", "Apache 2", "Apache 2.0", "BSD",],
    "CC BY": ["CC BY 4.0", "CC BY-SA 4.0", "CC BY-SA 3.0", ],
    "CC BY NC": ["CC BY-NC 4.0", "CC BY-NC-SA 4.0", "CC BY-NC-ND 4.0", "CC BY-NC-SA 3.0"],
    "GPL": ["GPL 3.0"],
    "Other / Unspecified": ["Custom", "Unspecified", "Unknown"]
    # "Other / Unspecified": [],
    # "Academic-only": [],
    # "Fully commerical, but must attribute": []
}

FORMAT_GROUPS = {
    "Zero-Shot Prompt": ["Zero-Shot Prompt"],
    "Few-Shot Prompt": ["Few-Shot Prompt"],
    "Chain-of-Thought Prompt": ["Chain-of-Thought Prompt"],
    "Multi-turn Dialog": ["Multi-turn Dialog"],
    "Response Ranking": ["Response Ranking"],
}

DOMAIN_GROUPS = {
    "Wikipedia": ["Wikipedia"],
    "Web": ["Web"],
    "News": ["News"],
    "Social Media": ["Social Media"],
    "Books": ["Books"],
    "Biomedical": ["Biomedical"],
    "Academic": ["Academic"],
    "Code": ["Code"],
    "Legal": ["Legal"],
}

LANGUAGE_GROUPS = {
    "English": ["English"],
    "French": ["French"],
    "Spanish": ["Spanish"],
    "Italian": ["Italian"],
    "Hindi": ["Hindi"],
    "German": ["German"],
    "Chinese": ["Chinese", "Chinese (Simplified)", "Chinese (Traditional)", "Mandarin Chinese", "Cantonese", "Yue Chinese"],
    "Arabic": ["Arabic", "Egyptian Arabic", "Mesopotamian Arabic", "Modern Standard Arabic", "Modern Standard Arabic (Romanized)", "Moroccan Arabic", "Ta’izzi-Adeni Arabic", "North Levantine Arabic", "South Levantine Arabic"],
    "Japanese": ["Japanese"],
    "Korean": ["Korean"],
    "Maltese": ["Maltese"],    
    "Persian": ["Persian", "Farsi", "Western Persian"],
    "Afro-Asiatic": ["Somali", "Tigrinya"],
    "Austronesian": ["Indonesian", "Maori", "Cebuano", "Samoan", "Waray", "Banjar (Latin script)", "Buginese", "Javanese"],
    "Austroasiatic": ["Vietnamese", "Thai", "Khmer", "Burmese", "Standard Malay"],
    "Turkish": ["Turkish"],
    "Other Indo-European": ["Portuguese", "Portugese (Brazilian)", "Catalan", "Russian", "Macedonian", "Estonian", "Latvian", "Polish", 'Romano-Serbian', 'Tosk Albanian', "Czech", "Romanian", "Dutch", "Galician", "Bulgarian", "Croatian", "Serbian", "Slovak", "Lithuanian", "Ukrainian", "Greek", "Modern Greek", "Belarusian", "Slovenian", "Luxembourgish", "Castilian", "Serbo-Croatian", 'Latin'],
    "Indian Peninsula": ["Bengali", "Telugu", "Nepali", "Kurdish", "Tamil", "Gujarati", "Kashmiri (Devanagari script)", "Eastern Panjabi", "Panjabi", "Punjabi", "Central Kanuri (Latin script)", "Assamese", "Marathi", "Odia", "Meitei (Bengali script)", "Bangla", "Chhattisgarhi", "Bhojpuri", "Maithili"],
    "Scandinavian": ["Finnish", "Swedish", "Norwegian", "Danish", "Icelandic", "Norwegian Bokmål", "Norwegian Nynorsk"],
    "Low Resource Languages": ["Haitian", "Malayalam", "Maltese", "Xhosa", "Yoruba", "Zhuang", "Awadhi", "Eastern Yiddish", "Plateau Malagasy", "Kiswahili", "Oromo", "Acehnese (Latin script)", "Sicilian", "Friulian", "Marwari", "Tulu", "Mizo", "Najdi Arabic", "Minangkabau (Latin script)", "Nuer", "Wolof", "Interlingue", "Fon", "Nigerian Fulfulde", "Crimean Tatar", "Ganda", "Tunisian Arabic", "Sardinian", "Mongolian", "Ewe", "Amharic", "Limburgish", "Lao", "Kinyarwanda", "Kamba", "Umbundu", "Asturian", "Kabyle", "West Central Oromo", "Azerbaijani", "Albanian", "Lingala", "Georgian", "Pashto", "Belarusian", "Western Armenian", "Tatar", "Western Frisian", "Bashkir", "Igbo", "Flemish", "Ilocano", "Acehnese (Arabic script)", "Nyanja", "Chuvash", "Breton", "Central Aymara", "Gaelic", "Chamorro", 'Luo', 'Southwestern Dinka', 'Banjar (Arabic script)', 'Halh Mongolian', 'Hausa', 'Malay', 'South Azerbaijani', 'Ghanaian Pidgin English', 'Irish', 'Ido', 'Swahili', 'Esperanto', 'Cornish', 'Kyrgyz', 'Bosnian', 'Kazakh', 'Occitan', 'Jingpho', 'Minangkabau (Arabic script)', 'Sanskrit', 'Sinhala', 'Welsh', 'Zulu', 'Basque', 'North Azerbaijani', 'Quechua', 'Sinhalese', 'Turkmen', 'Faroese','Shan', 'Southern Pashto', 'Interlingua', 'Akan', 'Kikuyu', 'Northern Kurdish', 'Kabuverdianu', 'Haitian Creole', 'Standard Tibetan', 'Khmer', 'Northern Sotho', 'Tamasheq (Latin script)', 'Kannada', 'Santali', 'Tumbuka', 'Kashmiri (Arabic script)', 'Burmese', 'Volapük', 'Northern Uzbek', 'Urdu', 'Kikongo', 'Swati', 'Sindhi', 'Standard Latvian', 'Ligurian', 'Silesian', 'Latgalian', 'Dari', 'Maltese', 'Kabiyè', 'Uighur', 'Pushto', 'Armenian', 'Bambara', 'Central Atlas Tamazight', 'Shona', 'Lombard', 'Southern Sotho', 'Ayacucho Quechua', 'Twi', 'Pangasinan', 'Rundi', 'Chokwe', 'Sango', 'Tamasheq (Tifinagh script)', 'Guarani', 'Luba-Kasai', 'Tagalog', 'Tajik', 'Magahi', 'Fijian', 'Papiamento', 'Venetian', 'Hungarian', 'Sundanese', 'Yiddish', 'Tsonga', 'Central Kurdish', 'Dzongkha', 'Tswana', 'Uyghur', 'Scottish Gaelic', 'Bemba', 'Afrikaans', 'Balinese', 'Central Kanuri (Arabic script)', 'Mossi', 'Hebrew', 'Kimbundu', 'Tok Pisin', 'Dyula', 'Uzbek', 'Kirghiz'],
    "Code": ["Java", "Python"],
}


TASK_CATEGORY_GROUPS = {
    'Question Answering': [
        "Question Answering", "Multiple-Choice QA (no trivia knowledge required)", "Extractive QA", "Closed-Book QA",
        "Information Extraction", "Question Understanding", "Forum QA"],
    "Translation": ["Translation", "Inverted Translation"],
    "Sentiment Analysis": ["Sentiment Analysis"],
    "Summarization": ["Summarization"],
    "Text Classification": [
        "Text Classification", "Text Categorization", "Title Generation", "Named Entity Recognition", 
        "Coreference Resolution", "Cause Effect Classification", "Text Matching"],
    "Natural Language Inference": ["Natural Language Inference", "Textual Entailment"],
    "Question Generation": [
        "Question Generation", "Inverted Multiple-Choice QA (no trivia knowledge required)", "Inverted Extractive QA"],
    "Toxic Language Detection": ["Toxic Language Detection"],
    "Chain-of-Thought": ["Chain-of-Thought"],
    "Dialog Generation": ["Dialogue Generation", "Dialog"],
    "Code Generation": ["Text to Code", "Program Synthesis", "Coding"],
    "Short Text Generation": ["Text Completion", "Paraphrasing", "Sentence Composition"],
    "Miscellaneous": ["Miscellaneous", "Misc."],
    "Open-form Text Generation": [
        "Inverted Natural Language Inference", "Inverted Summarization", "Inverted Sentiment Analysis",
        "Structured Data to Text"],
    "Brainstorming": ["Brainstorming"],
    "Creative Writing": ["Creative Writing"],
    "Code": ["Code Synthesis", "Code Generation", "Code Completion", "Code Summarization", "Code Repair", "Code Search", "Code Complexity Prediction"],
    "Alignment": ["RLHF"],
    "Roleplay": ["Roleplay"],
    "Other Tasks": [
        "Academic Tasks",
        "Paraphrase Identification",
        "Simplification",
        "Speaker Identification",
        "Inverted Structured Data to Text",
        "Wrong Candidate Generation",
        "Inverted Coreference Resolution",
        "Story Composition",
        "Pos Tagging",
        "Data to Text",
        "Topic Classification",
        "Inverted Closed-Book QA",
        "Inverted Next Sentence Prediction",
        "Next Sentence Prediction",
        "Paraphrasing Identification",
        "Inverted Paraphrasing Identification",
        "Answer Verification",
        "Text Simplification",
        "Commonsense Classification",
        "Program Execution",
        "Word Relation Classification",
        "Question Rewriting",
        "Fact Verification",
        "Dialogue Act Recognition",
        "Sentence Perturbation",
        "Word Semantics",
        "Dialog Context Generation",
        "Conversational Question Answering",
        "Inverted Topic Classification",
        "Text Quality Evaluation",
        "Mathematical QA",
        "Inverted Mathematical QA",
        "Coherence Classification",
        "Explanation",
        "Answerability Classification",
        "Linguistic Probing",
        "Stance Detection",
        "Dialogue State Tracking",
        "Gender Classification",
        "Grammar Error Correction",
        "Language Identification",
        "Fill in The Blank",
        "Keyword Tagging",
        "Inverted Grammatical Acceptability",
        "Grammatical Acceptability",
        "Inverted Punctuation Fixing",
        "Punctuation Fixing",
        "Inverted Language Modeling",
        "Language Modeling",
        "Casing Selection",
        "Inverted Casing Selection",
        "Inverted Question Answering",
        "Word Sense Disambiguation",
        "Inverted Word Sense Disambiguation",
        "Word Segmentation",
        "Inverted Word Segmentation",
        "Adversarial QA",
        "Context Generation",
        "Explanation Generation",
        "Dialog Turn Prediction",
        "Span Generation",
        "Intent Identification",
        "Word Analogy",
        "Question Decomposition",
        "Negotiation Strategy Detection",
        "Grammar Error Detection",
        "Stereotype Detection",
        "Style Transfer",
        "Entity Generation",
        "Number Conversion",
        "Sentence Compression",
        "Paper Review",
        "Overlap Extraction",
        "Poem Generation",
        "Preposition Prediction",
        "Ethics Classification",
        "Irony Detection",
        "Spam Classification",
        "Sentence Ordering",
    ]
}
